dflt: dbg

dbg:
	nmake -f TaskKeyHook.mak CFG="TaskKeyHook - Win32 Debug"
	nmake -f TrapKeys.mak CFG="TrapKeys - Win32 Debug"

rel:
	nmake -f TaskKeyHook.mak CFG="TaskKeyHook - Win32 Release"
	nmake -f TrapKeys.mak CFG="TrapKeys - Win32 Release"

all:	dbg rel
	
